name: pp
description: A package to convert numbers into strings to easily readable.
version: 1.0.0
homepage: https://github.com/lalit3102/roundNumbersSuffix.git

environment:
  sdk: '>=2.17.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
